[phases.setup]
nixPkgs = ["libxcb", "libGL", "glib", "libxcb-util"]

[phases.install]
cmds = [
    "pip install --no-cache-dir -r requirements.txt",
    "pip install --no-cache-dir 'opencv-python-headless==4.13.0.92' --force-reinstall"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
