[phases.setup]
nixPkgs = ["libxcb", "libGL", "glib"]

[phases.install]
cmds = [
    "pip install --no-cache-dir -r requirements.txt",
    "pip uninstall -y opencv-python",
    "pip install --no-cache-dir opencv-python-headless==4.13.0.92"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
